In [1]:
import numpy

# Creating arrays

## Python List

In [2]:
normal_list = [1, 2, 3, 4, 5]

In [3]:
type(normal_list)

list

## Numpy Array

In [4]:
numpy.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
array = numpy.array(normal_list)

In [6]:
type(array)

numpy.ndarray

## Dimensions and Shape

In [7]:
array.ndim

1

In [8]:
array.shape

(5,)

### Creating a bidimensional array
We can uses many lists or other numpy arrays

In [9]:
list01 = [0, 2, 4, 6, 8]
list02 = [1, 3, 5, 7, 9]

In [10]:
array_d2 = numpy.array([list01, list02])

In [11]:
array_d2

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [12]:
type(array_d2)

numpy.ndarray

In [13]:
array_d2.ndim

2

The first number shown how many lines have and the second number shown how many elements exist in each line

In [14]:
array_d2.shape

(2, 5)

## Creating arrays

## zeros
Create an array and fullfill with zeros

In [15]:
numpy.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

You can a multdimencional array with zeros

In [16]:
numpy.zeros((5,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## ones
Create an array and fullfill with ones

In [17]:
numpy.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

You can a multdimencional array with ones

In [18]:
numpy.ones((5, 10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## empty
Create an empty array, by default numpy will fill with zeros

In [19]:
numpy.empty((5, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

## arange
Create an array with sequence of numbers, is similar a range python function

In [20]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can use slice, the first parameter is a start point, the second is a stop point and the third is the step

In [21]:
numpy.arange(2, 40, 3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

## Data types for arrays
Numpy allow us to decide the data type which will be applied in each element

In [22]:
array_int = numpy.array([1, 2, 3, 4, 5], dtype=numpy.int32)
array_float = numpy.array([1, 2, 3, 4, 5], dtype=numpy.float64)

In [23]:
array_int

array([1, 2, 3, 4, 5], dtype=int32)

In [24]:
array_float

array([ 1.,  2.,  3.,  4.,  5.])

We can check the type using .dtype

In [25]:
array_int.dtype

dtype('int32')

In [26]:
array_float.dtype

dtype('float64')

### Convert data type
The method .astype allow us to convert array data types

In [42]:
array_int.astype(numpy.float128)

array([ 1.0,  2.0,  3.0,  4.0,  5.0], dtype=float128)

In [44]:
array_float.astype(numpy.int32)

array([1, 2, 3, 4, 5], dtype=int32)

# Mathmatical operations on arrays

In [69]:
array_x = numpy.array([1, 2, 4, 6, 8])
array_y = numpy.array([10, 13, 15, 17, 19])

array_2d_x = numpy.array([array_x, array_y])
array_2d_y = numpy.array([array_x, array_y])

## Sum

In [70]:
array01 + array02

array([ 1,  5,  9, 13, 17])

In [71]:
array_2d_x + array_2d_y

array([[ 2,  4,  8, 12, 16],
       [20, 26, 30, 34, 38]])

## Subtraction

In [72]:
array02 - array01

array([1, 1, 1, 1, 1])

In [73]:
array_2d_x - array_2d_y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## Multiplication

In [74]:
array02 * array01

array([ 0,  6, 20, 42, 72])

In [75]:
array_2d_x * array_2d_y

array([[  1,   4,  16,  36,  64],
       [100, 169, 225, 289, 361]])

## Division

In [76]:
array01 / array02

array([ 0.        ,  0.66666667,  0.8       ,  0.85714286,  0.88888889])

In [78]:
array_2d_y / array_2d_x

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])